### ISSUE TITLE
Bug: add_nflib_bg_affine_shared_pal is not generating .img files

### ISSUE THREAD

**Issue by EthGaming101** [AntonioND/architectds#4]
Looking through the console output in warning level 3, it seems that grit is trying to look for a .bin file as the shared palette. Considering affine backgrounds need to share the same palette if both of them are used in one screen, this is pretty important for NFLib's mode 2.

I'm using BlocksDS with MSYS2 on MINGW64, by the way.

**Comment by EthGaming101** [comment]
Okay, looks like it works correctly if I use the Wonderful Toolchain Shell, and follow the setup instructions for Windows specifically.

**Comment by AntonioND** [comment]
I assume you also have devkitARM installed? If you aren't using the right shell it may be using grit from there, yeah...

**Comment by EthGaming101** [comment]
No, I do not.
