### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by KiwifruitDev** [AntonioND/architectds#5]
Hello, I noticed that there is no license specified. Could you please clarify any terms necessary?

My project is licensed under the MIT License, so I'm being very careful as to not include GPL or other incompatible licensed software.

I would appreciate it, thank you.

**Comment by AntonioND** [comment]
While there is no license text in the repository, the files themselves specify that the license is MIT: https://github.com/AntonioND/architectds/blob/f04dafa739837bd0336bf208a627ca165d1c73bf/architectds/architectds.py#L1

I'll add the file later.

EDIT: In any case, this is a build system. I think that even if it was GPL it wouldn't affect your own code as this isn't linked with your code.

**Comment by AntonioND** [comment]
Fixed! https://github.com/AntonioND/architectds/commit/ccfc657a68408f2f7933665e2b99444dc04d9917
